Fixed uv rotation
NOAA-GFDL/CEFI-regional-MOM6 pull request #94
Opened 2024-09-19 19:23 UTC by yichengt900

We identified a bug in our Python pre-processing tool related to the sign of the UV rotation. The sign was incorrect, so we have reversed it and verified the fix in both the `NEP` and `ARCTIC` domains (see figures below; the black arrow represents true north, the green indicates the previous rotation, and the red shows the corrected rotation). The updated rotation should now accurately map the Earth’s true UV coordinates to the model’s coordinate system.

`NEP`:
![nep_test](https://github.com/user-attachments/assets/88656bf2-1a0a-484d-bdba-f80aeb3064bd)

`ARC`:
![arc_test](https://github.com/user-attachments/assets/3460ad46-b38e-4b0f-9c88-e64291020a84)

2024-09-19 20:31 UTC, theresa-morrison approved these changes
The change looks good to me. Thanks for testing this!

2024-09-19 20:32 UTC, theresa-morrison commented
I sent Kate an email about this PR, hopefully she is able to confirm if the Arctic OBCs we have been using have this bug.

2024-09-19 23:20 UTC, charliestock commented
Thanks for raising and addressing this Yi-Cheng, Andrew and Vimal.  Looking forward to seeing the improvements this yields in the coming weeks.  Perhaps we could include a comment in the code to clarify how the angle is defined in the MOM6 grid?

2024-09-20 12:36 UTC, charliestock commented
I think we may still have a bit more work to do on this.  

Consider a domain that is rotated by pi/6 in the counterclockwise direction. (e.g., perhaps one rotated such that the new north-south is aligned with the alongshore direction of the California Current).  If we subject this domain to a truly southward current of -1 along its northern boundary,  in the rotated frame, the old method yields u = -0.5 and v = -0.866.  As expected, the current is still predominantly southward but the rotation has introduced a westward (offshore) flow.  The total magnitude of the current remains 1.  The new method also gives v = -0.866, but gives u = +0.5.  Rather then creating a offshore flow as expected, it creates an inshore flow.

I need to spend some more time with this to unpack all the possibilities and fully convince myself, but the old code seems to give the right answer in the case above.

2024-09-20 13:12 UTC, andrew-c-ross requested changes
I think this was an unnecessary panic by me. Thanks @charliestock for showing me the light.

The original formula is for a clockwise rotation of the angle, while the new formula is for a counterclockwise rotation. I thought it was right to switch to the new because angle_dx for our model grids is the counterclockwise rotation relative to true earth. I should have realized that what we actually need to do is coordinate rotation, not vector rotation, in which case the original formula is correct for a counterclockwise rotation of the coordinates. (https://mathworld.wolfram.com/RotationMatrix.html)

You can see this in @yichengt900 's first figure of the NEP. A true north (0, +v) vector should be nearly a (+v, 0) vector on the model coordinates. In the old formula we'd have u ~= sin(angle) * v which yields +v since sin(angle) is positive. In the new formula it would yield -v.

2024-09-20 16:22 UTC, yichengt900 commented
Thank you, @charliestock and @andrew-c-ross, for your thorough investigation and valuable insights. After reviewing the grid generation source code, I can confirm that the `angle_dx` in the `ocean_hgrid.nc` file represents the orientation of the local coordinate system relative to the spherical Earth, measured counterclockwise. Therefore, if our goal is indeed to perform **coordinate rotation** rather than vector rotation, the original formulation appears to be correct for this purpose.

If either of you could kindly confirm this as well, I will proceed to close the PR to prevent any further confusion for users.

2024-09-20 17:58 UTC, andrew-c-ross commented
I talked to Charlie and Matt and we're convinced that we should close this. However, it would be good to add more details to the function docstring so that we remember that the angle_dx is the angle to go counterclockwise from the true earth east to the model east, and that this function is doing a coordinate transformation from true earth coordinates to model coordinates.

2024-09-20 17:58 UTC, closed without merging